// <auto-generated />
namespace Dareurbody.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addreservationtable6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreservationtable6));
        
        string IMigrationMetadata.Id
        {
            get { return "201903230411155_addreservationtable6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
